services:
  client-react-nginx:
    image: client-react:0
    ports:
      - 5173:8080
    restart: unless-stopped
  api-node:
    image: api-node:0
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: unless-stopped
  db:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=foobarbaz

